name: Build & Deploy Sphinx Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system packages (pandoc, optional graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc graphviz

      - name: Install Python deps
        run: |
          if [ -f sphinx-requirements.txt ]; then
            pip install -r sphinx-requirements.txt
          else
            pip install sphinx
          fi

      - name: Build Sphinx
        run: |
          cd mooc
          sphinx-build -b html . _build/html

      - name: Build Sphinx
        run: sphinx-build -b html . _build/html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
